# Target with \
#   multi line comment
target3:
	@echo "Target 3"

# comment with slash \
slash:
	@echo "This target has a slashed comment"

# comment with slash and space \ 
slash-and-space:
	@echo "This target has a slashed comment with space"

tricky-target:
	@echo "This\
# target \
target: \
	tries to trick the regex!"

  indented-target:
	@echo "This target is indented"

# indented commented target!
   indentend-commented-target:
	@echo "This target is indented and commented"
